### PR TITLE
Design updates.

### PR DESCRIPTION
**Pull request by wsalesky**
@mMoliere Here is the design updates for the forms, there is one major bug that I am still working out, but I would like you to get these up so you can take a look at them and let me know if you spot any other problem areas. This will probably be to big a pull request for the webhooks, so you or I can manually upload the new files. Just let me know if you want me to do it.

### CODE REVIEW

**Comment by mMoliere** [comment]
@wsalesky Great job! I will take inspect it for errors. Thank you very much!

**Comment by wsalesky** [comment]
@mMoliere looks like the webhooks were incomplete (to many files updated at once), do you need help getting the new files up?

**Comment by mMoliere** [comment]
@wsalesky No, the updates were sent to the server. There are a few minor issues that should be easy to fix. They mostly concern improvements which you made last week, which are now missing again. But something like this is to be expected when the changes are not fed into the repository through the usual way. I am preparing issues for them.

**Comment by mMoliere** [comment]
@wsalesky It looks really good now! Thank you for all your hard work! 

Please see if you solve #98 and #236.

**Comment by wsalesky** [comment]
@mMoliere #98 should be fixed. Try a hard refresh. I will work on the other one later tonight or tomorrow am. Are we getting an .xar for the srophe application tomorrow? I want to save some time to test that one as well.

**Comment by mMoliere** [comment]
@wsalesky Yes, as I understood Hélène, we will get another .xar file today.

**Pull request merged**
